version: '3.8'

services:
  rclone-mergerfs:
    build: .
    volumes:
      - /home/senpai/Cloud:/home/senpai/Cloud
      - /home/senpai/JellyCloud:/home/senpai/JellyCloud
      - /var/run/docker.sock:/var/run/docker.sock  # Allows Docker CLI access
    cap_add:
      - FOWNER
      - SYS_ADMIN
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Asia/Kolkata
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    depends_on:
      - rclone-mergerfs

  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - /home/senpai/Downloads:/downloads
      - /home/senpai:/data  # Assuming your media files are in JellyCloud
    restart: always
    user: 1002:1002
    environment:
      - TZ=Asia/Kolkata
      - UN_QUIET=false
      - UN_DEBUG=false
      - UN_ERROR_STDERR=false
      - UN_LOG_QUEUES=1m
      - UN_LOG_FILES=10
      - UN_LOG_FILE_MB=10
      - UN_INTERVAL=2m
      - UN_START_DELAY=1m
      - UN_RETRY_DELAY=5m
      - UN_MAX_RETRIES=3
      - UN_PARALLEL=1
      - UN_FILE_MODE=0644
      - UN_DIR_MODE=0755
      - UN_ACTIVITY=false
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_SONARR_0_API_KEY=
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_RADARR_0_API_KEY=
      - UN_LIDARR_0_URL=http://lidarr:8686
      - UN_LIDARR_0_API_KEY=
      - UN_READARR_0_URL=http://readarr:8787
      - UN_READARR_0_API_KEY=
    depends_on:
      - rclone-mergerfs

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Asia/Kolkata
    volumes:
      - /home/senpai/Files/AppData/Config/Jellyfin:/config
      - /home:/home
    ports:
      - 8096:8096
      - 8920:8920 # optional
      - 7359:7359/udp # optional
      - 1900:1900/udp # optional
    restart: unless-stopped
    depends_on:
      - rclone-mergerfs

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Kolkata
    ports:
      - 5055:5055
    volumes:
      - /home/senpai/Files/AppData/Config/Jellyfin:/app/config
    restart: unless-stopped
    depends_on:
      - rclone-mergerfs

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Asia/Kolkata
    volumes:
      - /home/senpai/Files/AppData/Config/bazarr:/config
      - /home/senpai:/data # optional
    ports:
      - 6767:6767
    restart: unless-stopped
    depends_on:
      - rclone-mergerfs

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Asia/Kolkata
    volumes:
      - /home/senpai/Files/AppData/Config/Sonarr/data:/config
      - /home/senpai:/data
      - /home/senpai/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    depends_on:
      - rclone-mergerfs

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Asia/Kolkata
    volumes:
      - /home/senpai/Files/AppData/Config/Radarr/data:/config
      - /home/senpai:/data
      - /home/senpai/Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - rclone-mergerfs
